- name: Setup BRTFS   
  become: true
  block:
    - name:  Setup BRTFS -> Replace ExecStart line in grub-btrfsd service
      ansible.builtin.replace:
        path: /etc/systemd/system/grub-btrfsd.service
        regexp: '^ExecStart=/usr/bin/grub-btrfsd --syslog /.snapshots'
        replace: 'ExecStart=/usr/bin/grub-btrfsd --syslog --timeshift-auto'

    - name: Setup BRTFS -> Enable grub-btrfsd service
      ansible.builtin.systemd:
        name: grub-btrfsd
        enabled: yes

    - name: Setup BRTFS -> Start grub-btrfsd service
      ansible.builtin.systemd:
        name: grub-btrfsd
        state: started