- name: Setup personal computer
  hosts: local
  roles:
    - aur
    - applications
    - grub
    - dotfiles
    - terminal
    - gnome_icon_theme
    - gnome_extensions
    - gnome_desktop
    - brtfs_snapshots