- name: Check if GDM Settings exists
  ansible.builtin.stat:
    path: "{{ gdm_settings_file_path }}"
  register: is_gdm_settings_installed

- name: Setup GDM Settings
  when: not is_gdm_settings_installed.stat.exists
  block:
    - name: Setup GDM Settings -> Install GDM Settings
      become: true
      yay:
        name:
          - aur/gdm-settings
        state: present
    - name: Setup GDM Settings -> Remove Logo
      become: true
      become_user: "gdm"
      ansible.builtin.command: gsettings set org.gnome.login-screen logo ''
