- name: Applications -> Update
  become: true
  ansible.builtin.pacman:
    upgrade: true

- name: Applications -> Install
  become: true
  block:
    - name: Applications -> Install -> Dependencies
      ansible.builtin.pacman:
        name:
          - git
          - yay
          - ttf-fira-code
          - ttf-jetbrains-mono
        state: present

    - name: Applications -> Install -> Packages from YAY
      yay:
        name:
          - github-cli
          - proton-vpn-gtk-app
          - aur/docker-desktop
          - chaotic-aur/yubico-authenticator-bin
          - chaotic-aur/asdf-vm
          - chaotic-aur/visual-studio-code-bin
          - chaotic-aur/gdm-settings
        state: present

    - name: Applications -> Install -> Packages from flatpak
      community.general.flatpak:
        name:
          - app.zen_browser.zen
          - md.obsidian.Obsidian
          - com.bitwarden.desktop
          # Image Utils
          - com.github.huluti.Coulr
          - io.gitlab.adhami3310.Converter
          - page.kramo.Sly
          - dev.geopjr.Calligraphy
          # Development
          - rest.insomnia.Insomnia
          - io.beekeeperstudio.Studio
          # Chat
          - com.discordapp.Discord
          - org.telegram.desktop
          # Media
          - com.spotify.Client
          - tv.plex.PlexDesktop
          - org.gnome.Decibels
          # Games
          - com.valvesoftware.Steam
          - com.usebottles.bottles
        state: latest
